# Generated by Django 3.0.5 on 2021-01-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210109_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='userid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
